import { ArrowDownToLine, AudioLines, ChevronDown, ExternalLink, FileAudio, FileText, FolderOpen, HelpCircle, Info, Mail, MessageSquareText, Redo2, Save, Undo2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useEffect, useRef } from 'react';
import { homeUrl, mvStudioGuideUrl } from '../domain/about';
import { LanguagePicker } from './LanguagePicker';
type Props = { title:string; saveStatus:string; canUndo:boolean; canRedo:boolean; disabled:boolean; rename:(title:string)=>void; openProject:()=>void; importAudio:()=>void; importLyrics:()=>void; saveProject:()=>void; undo:()=>void; redo:()=>void; openGuide:()=>void; openTiming:()=>void; openSettings:()=>void; openAbout:()=>void; openContact:()=>void; openFeedback:()=>void; exportVideo:()=>void };
const close = (event: React.MouseEvent) => { const menu = event.currentTarget.closest('details'); menu?.removeAttribute('open'); menu?.querySelector('summary')?.focus(); };
function Menu({ label, children }: { label:string; children:React.ReactNode }) {
  const menu = useRef<HTMLDetailsElement>(null), panel = useRef<HTMLDivElement>(null);
  const fit = () => {
    if (!menu.current?.open || !panel.current) return;
    const anchor = menu.current.getBoundingClientRect();
    const width = panel.current.getBoundingClientRect().width;
    panel.current.style.left = `${Math.max(8 - anchor.left, Math.min(0, innerWidth - 8 - anchor.left - width))}px`;
    panel.current.style.maxHeight = `${Math.max(80, innerHeight - anchor.bottom - 14)}px`;
  };
  useEffect(() => {
    const dismiss = (event: PointerEvent) => { if (menu.current?.open && !menu.current.contains(event.target as Node)) menu.current.open = false; };
    window.addEventListener('resize', fit); document.addEventListener('pointerdown', dismiss);
    return () => { window.removeEventListener('resize', fit); document.removeEventListener('pointerdown', dismiss); };
  }, []);
  return <details ref={menu} className="app-menu" onToggle={fit} onKeyDown={event => { if (event.key === 'Escape' && event.currentTarget.open) { event.preventDefault(); event.currentTarget.open = false; event.currentTarget.querySelector('summary')?.focus(); } }}><summary>{label}<ChevronDown size={11}/></summary><div ref={panel} className="app-menu-popover">{children}</div></details>;
}
export function AppHeader(props: Props) { const { t } = useTranslation(); return <header className="topbar app-header"><a className="brand" href="#" onClick={event => event.preventDefault()} aria-label="UseSuno MV Studio"><span className="brand-symbol"><AudioLines size={20}/></span><strong>UseSuno<span>MV Studio</span></strong></a><nav className="app-menus" aria-label={t('menu.application')}><Menu label={t('menu.file')}><button onClick={event => { close(event); props.openProject(); }}><FolderOpen size={14}/><span>{t('menu.openProject')}</span></button><button onClick={event => { close(event); props.importAudio(); }}><FileAudio size={14}/><span>{t('menu.importAudio')}</span></button><button onClick={event => { close(event); props.importLyrics(); }}><FileText size={14}/><span>{t('menu.importLyrics')}</span></button><hr/><button onClick={event => { close(event); props.saveProject(); }}><Save size={14}/><span>{t('app.saveProject')}</span></button></Menu><Menu label={t('menu.edit')}><button disabled={!props.canUndo} onClick={event => { close(event); props.undo(); }}><Undo2 size={14}/><span>{t('app.undo')}</span><kbd>⌘Z</kbd></button><button disabled={!props.canRedo} onClick={event => { close(event); props.redo(); }}><Redo2 size={14}/><span>{t('app.redo')}</span><kbd>⇧⌘Z</kbd></button></Menu><button className="menu-about" onClick={props.openSettings}>{t('menu.settings')}</button><Menu label={t('menu.help')}><button onClick={event => { close(event); props.openGuide(); }}><HelpCircle size={14}/><span>{t('menu.guide')}</span></button><button onClick={event => { close(event); props.openTiming(); }}><FileText size={14}/><span>{t('menu.timing')}</span></button><a className="menu-link" href={mvStudioGuideUrl} target="_blank" rel="noreferrer" onClick={close}><ExternalLink size={14}/><span>{t('menu.mvGuide')}</span></a><hr/><a className="menu-link" href={homeUrl} target="_blank" rel="noreferrer" onClick={close}><ExternalLink size={14}/><span>{t('menu.home')}</span></a></Menu><Menu label={t('menu.about')}><button onClick={event => { close(event); props.openAbout(); }}><Info size={14}/><span>{t('menu.aboutProduct')}</span></button><button onClick={event => { close(event); props.openContact(); }}><Mail size={14}/><span>{t('menu.contact')}</span></button><button onClick={event => { close(event); props.openFeedback(); }}><MessageSquareText size={14}/><span>{t('menu.feedback')}</span></button></Menu></nav><div className="project-heading"><input key={props.title} aria-label={t('app.projectName')} defaultValue={props.title} maxLength={300} onBlur={event => { const title=event.target.value.trim(); if(title&&title!==props.title) props.rename(title); }}/><span className="save-state">{props.saveStatus}</span></div><div className="top-actions"><LanguagePicker/><button className="primary" data-tour="export" disabled={props.disabled} onClick={props.exportVideo}><ArrowDownToLine size={15}/>{t('app.export')}</button></div></header>; }
