import { useEffect, useState } from 'react';
import { SlidersHorizontal, Check, ImagePlus, Trash2, WandSparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { backgrounds, palettes, templates, type Project } from '../domain/model';
import { FontPicker } from './FontPicker';
import { Modal } from './Modal';
const traditionalTemplateNames: Partial<Record<Project['template'], string>> = { 'folia-partita':'雲階','folia-tilt':'傾訴','folia-claddagh':'迴環','folia-diorama':'鏡台','folia-aurora':'極光','folia-pendolo':'時計','folia-sonnet':'商籟','folia-still':'靜幀' };
function ImagePreview({ blob, label, emptyLabel }: { blob: Blob | null; label: string; emptyLabel: string }) {
  const [url, setUrl] = useState('');
  useEffect(() => { if (!blob) { setUrl(''); return; } const next = URL.createObjectURL(blob); setUrl(next); return () => URL.revokeObjectURL(next); }, [blob]);
  return url ? <img src={url} alt={label}/> : <span className="monet-empty">{emptyLabel}</span>;
}
// Presentation controls persist in the project and are shared by both render paths.
export function Inspector({ project: p, change, importFont, installFont, importTemperaImages, removeTemperaImage, coverBlob, monetPortraitBlob, importMonetPortrait, clearMonetPortrait }: { project: Project; change: (patch: Partial<Project>) => void; importFont: () => void; installFont: (blob: Blob, family: string) => Promise<void>; importTemperaImages: () => void; removeTemperaImage: (id: string) => Promise<void>; coverBlob: Blob | null; monetPortraitBlob: Blob | null; importMonetPortrait: () => void; clearMonetPortrait: () => void }) {
  const { t, i18n } = useTranslation();
  const isChinese = (i18n.resolvedLanguage || i18n.language).startsWith('zh');
  const isTraditional = (i18n.resolvedLanguage || i18n.language) === 'zh-TW';
  const [pickerOpen, setPickerOpen] = useState(false);
  const selectedTemplate = templates.find(item => item.id === p.template) ?? templates[0];
  const choose = (id: Project['template']) => { change({ template: id }); setPickerOpen(false); };
  const name = (item: typeof templates[number]) => !isChinese ? item.english.replace(' · Folia','') : isTraditional ? traditionalTemplateNames[item.id] || item.name : item.name;
  const art = (id: string) => <span className={`template-art ${id === 'folia-fume' ? 'article' : id === 'folia-classic' ? 'flow' : 'tilt'}`} aria-hidden="true">{!isChinese ? <><i>LYRIC</i><i>MOTION</i></> : id === 'folia-fume' ? <><i>把日子</i><i>{isTraditional?'寫成詩':'写成诗'}</i><i>{isTraditional?'讓風讀':'让风读'}</i></> : id === 'folia-classic' ? <><i>風</i><i>與</i><i>詩</i></> : <><i>{isTraditional?'寫成':'写成'}</i><i>{isTraditional?'一首詩':'一首诗'}</i></>}</span>;
  return <aside className="inspector" data-tour="inspector"><div className="panel-title"><h2>{t('inspector.title')}</h2><SlidersHorizontal size={15}/></div><section className="inspector-section animation-summary"><div className="section-label">{t('inspector.animation')} <span>{t('inspector.styles', { count: templates.length })}</span></div><button className="template-current" onClick={() => setPickerOpen(true)}>{art(selectedTemplate.id)}<span className="template-copy"><small>{t('inspector.selected')}</small><strong>{name(selectedTemplate)}</strong><em>{isChinese ? selectedTemplate.english : 'Folia visualizer'}</em></span><WandSparkles size={15}/></button><button className="browse-templates" onClick={() => setPickerOpen(true)}>{t('inspector.change')}<span>→</span></button></section>
    <section className="inspector-section"><div className="section-label">{t("inspector.background")} <span>{t("inspector.independent")}</span></div><div className="background-list">{backgrounds.map(item => <button key={item.id} className={p.background === item.id ? 'selected' : ''} onClick={() => change({ background: item.id })}><span className={`background-chip ${item.id}`}/><span><strong>{t(`background.${item.id}.name`)}</strong><small>{t(`background.${item.id}.description`)}</small></span>{p.background === item.id ? <Check size={13}/> : null}</button>)}</div><div className="section-label response-title">{t("inspector.reactivity")} <span>{t("inspector.previewExport")}</span></div><div className="segmented response-modes">{([['off',t("inspector.off")],['gentle',t("inspector.gentle")],['rhythmic',t("inspector.rhythmic")]] as const).map(([value,label]) => <button key={value} className={p.audioReactivity === value ? 'selected' : ''} onClick={() => change({ audioReactivity: value })}>{label}</button>)}</div>{p.audioReactivity !== 'off' ? <label className="range-label">{t("inspector.amount")} <span>{Math.round(p.audioReactivityAmount * 100)}%</span><input aria-label={t('aria.musicResponse')} type="range" min="0" max="1" step="0.05" value={p.audioReactivityAmount} onChange={e => change({ audioReactivityAmount: Number(e.target.value) })}/></label> : null}<p className="field-note">{t('inspector.reactivityNote')}</p></section>
    {p.template === 'folia-tempera' ? <section className="inspector-section"><div className="section-label">{t('tempera.pool')} <span>{p.temperaLayerImages.length} / 16 · {t('tempera.saved')}</span></div><button className="font-upload" disabled={p.temperaLayerImages.length >= 16} onClick={importTemperaImages}><ImagePlus size={13}/>{t('tempera.add')}</button><div className="tempera-pool">{p.temperaLayerImages.map(image => <div className="tempera-item" key={image.id}><div className="tempera-title"><span title={image.name}>{image.name}</span><button title={t('tempera.remove',{name:image.name})} aria-label={t('tempera.remove',{name:image.name})} onClick={() => void removeTemperaImage(image.id)}><Trash2 size={12}/></button></div><div className="tempera-controls"><label>{t('tempera.horizontal')}<select aria-label={`${image.name} · ${t('tempera.horizontal')}`} value={image.align} onChange={e => change({ temperaLayerImages: p.temperaLayerImages.map(item => item.id === image.id ? { ...item, align: e.target.value as typeof image.align } : item) })}><option value="left">{t('tempera.left')}</option><option value="center">{t('tempera.center')}</option><option value="right">{t('tempera.right')}</option><option value="free">{t('tempera.free')}</option></select></label><label>{t('tempera.vertical')}<select aria-label={`${image.name} · ${t('tempera.vertical')}`} value={image.verticalAlign} onChange={e => change({ temperaLayerImages: p.temperaLayerImages.map(item => item.id === image.id ? { ...item, verticalAlign: e.target.value as typeof image.verticalAlign } : item) })}><option value="top">{t('tempera.top')}</option><option value="center">{t('tempera.center')}</option><option value="bottom">{t('tempera.bottom')}</option><option value="free">{t('tempera.free')}</option></select></label></div><label className="tempera-range">{t('tempera.scale')} <span>{Math.round(image.scale * 100)}%</span><input aria-label={`${image.name} · ${t('tempera.scale')}`} type="range" min="0.1" max="2" step="0.05" value={image.scale} onChange={e => change({ temperaLayerImages: p.temperaLayerImages.map(item => item.id === image.id ? { ...item, scale: Number(e.target.value) } : item) })}/></label><label className="tempera-range">{t('tempera.opacity')} <span>{Math.round(image.opacity * 100)}%</span><input aria-label={`${image.name} · ${t('tempera.opacity')}`} type="range" min="0" max="1" step="0.05" value={image.opacity} onChange={e => change({ temperaLayerImages: p.temperaLayerImages.map(item => item.id === image.id ? { ...item, opacity: Number(e.target.value) } : item) })}/></label></div>)}</div></section> : null}
    {p.template === 'folia-monet' ? <section className="inspector-section monet-panel"><div className="section-label">{t('monet.portrait')} <span>{t('monet.saved')}</span></div><div className="monet-assets"><button className={p.monetPortraitSource === 'cover' ? 'selected' : ''} disabled={!coverBlob} onClick={() => change({ monetPortraitSource: 'cover' })}><ImagePreview blob={coverBlob} label={t('monet.embeddedCover')} emptyLabel={t('monet.noImage')}/><span><strong>{t('monet.songCover')}</strong><small>{coverBlob ? t('monet.fromAudio') : t('monet.noCover')}</small></span>{p.monetPortraitSource === 'cover' && coverBlob ? <Check size={12}/> : null}</button><button className={p.monetPortraitSource === 'custom' ? 'selected' : ''} onClick={importMonetPortrait}><ImagePreview blob={monetPortraitBlob} label={t('monet.customPortrait')} emptyLabel={t('monet.noImage')}/><span><strong>{t('monet.customImage')}</strong><small>{p.monetPortraitName || t('monet.uploadHint')}</small></span>{p.monetPortraitSource === 'custom' && monetPortraitBlob ? <Check size={12}/> : null}</button></div><div className="monet-actions"><button onClick={importMonetPortrait}><ImagePlus size={12}/>{monetPortraitBlob ? t('monet.replace') : t('monet.upload')}</button><button disabled={!monetPortraitBlob} onClick={clearMonetPortrait}><Trash2 size={12}/>{t('monet.remove')}</button></div><div className="section-label monet-subtitle">{t('monet.shape')}</div><div className="segmented"><button className={p.monetPortraitStyle === 'square' ? 'selected' : ''} onClick={() => change({ monetPortraitStyle: 'square' })}>{t('monet.square')}</button><button className={p.monetPortraitStyle === 'rectangular' ? 'selected' : ''} onClick={() => change({ monetPortraitStyle: 'rectangular' })}>{t('monet.portraitShape')}</button></div><label className="range-label">{t('monet.position')} <span>{p.monetPortraitOffsetX > 0 ? '+' : ''}{p.monetPortraitOffsetX}px</span><input aria-label={t('monet.position')} type="range" min="-240" max="240" step="5" value={p.monetPortraitOffsetX} onChange={e => change({ monetPortraitOffsetX: Number(e.target.value) })}/></label><div className="section-label monet-subtitle">{t('monet.spectrum')}</div><label className="toggle-label"><span>{t('monet.showSpectrum')}</span><input type="checkbox" checked={p.monetAudioVisualization} onChange={e => change({ monetAudioVisualization: e.target.checked })}/></label>{p.monetAudioVisualization ? <div className="segmented response-modes"><button className={p.monetAudioStyle === 'bar' ? 'selected' : ''} onClick={() => change({ monetAudioStyle: 'bar' })}>{t('monet.bars')}</button><button className={p.monetAudioStyle === 'line' ? 'selected' : ''} onClick={() => change({ monetAudioStyle: 'line' })}>{t('monet.curve')}</button></div> : null}</section> : null}
    <section className="inspector-section"><div className="section-label">{t("inspector.ratio")}</div><div className="segmented">{(['16:9', '9:16', '1:1'] as const).map(r => <button key={r} className={p.ratio === r ? 'selected' : ''} onClick={() => change({ ratio: r })}><span className={`ratio-icon r${r.replace(':', '')}`}/>{r}</button>)}</div></section>
    <section className="inspector-section"><div className="section-label">{t("inspector.palette")}</div><div className="swatches">{(Object.keys(palettes) as Project['palette'][]).map(key => <button key={key} title={t(`palette.${key}`)} aria-label={t(`palette.${key}`)} className={p.palette === key ? 'selected' : ''} style={{ background: palettes[key].bg, color: palettes[key].ink }} onClick={() => change({ palette: key })}><span style={{ background: palettes[key].accent }}/>{p.palette === key && <Check size={13}/>}</button>)}</div></section>
    <section className="inspector-section"><div className="section-label">{t("inspector.typography")}</div><FontPicker project={p} change={change} importFont={importFont} installFont={installFont}/><label className="range-label">{t("inspector.fontSize")} <span>{Math.round(p.fontScale * 100)}%</span><input aria-label={t('aria.textSize')} type="range" min="0.5" max="1.7" step="0.05" value={p.fontScale} onChange={e => change({ fontScale: Number(e.target.value) })}/></label><label className="range-label">{t("inspector.motion")} <span>{p.intensity.toFixed(1)}×</span><input aria-label={t('aria.motionAmount')} type="range" min="0.3" max="2" step="0.1" value={p.intensity} onChange={e => change({ intensity: Number(e.target.value) })}/></label></section>
    <section className="inspector-section"><label className="toggle-label"><span>{t('inspector.autoIntro')}</span><input type="checkbox" checked={p.autoIntro !== false} onChange={e => change({ autoIntro: e.target.checked })}/></label><p className="field-note">{t(p.template === 'folia-monet' || p.template === 'folia-cappella' ? 'inspector.autoIntroNativeNote' : 'inspector.autoIntroNote')}</p></section>
    <section className="inspector-section"><div className="section-label">{t("inspector.sync")}</div><label className="offset-label">{t("inspector.offset")} <div><input aria-label={t('aria.lyricOffset')} type="number" min="-3600" max="3600" step="0.1" value={p.offset} onChange={e => { const value = Number(e.target.value); if (Number.isFinite(value)) change({ offset: Math.min(3600, Math.max(-3600, value)) }); }}/><span>{t("inspector.seconds")}</span></div></label><p className="field-note">{t('inspector.offsetNote')}</p><label className="toggle-label"><span>{t("inspector.estimated")}</span><input type="checkbox" checked={p.estimatedReveal} onChange={e => change({ estimatedReveal: e.target.checked })}/></label><p className="field-note">{t('inspector.estimatedNote')}</p></section>
    <div className="inspector-foot"><span className="status-dot"/> {t('inspector.renderer')}</div>
    {pickerOpen && <Modal title={t('inspector.choose')} close={() => setPickerOpen(false)} wide><div className="template-picker-grid">{templates.map(item => <button key={item.id} className={`template-picker-option ${p.template === item.id ? 'selected' : ''}`} onClick={() => choose(item.id)}>{art(item.id)}<span className="template-copy"><strong>{name(item)}</strong><small>{isChinese ? item.english : `Style ${item.number}`}</small></span>{p.template === item.id && <Check size={14}/>}</button>)}</div></Modal>}
  </aside>;
}
