import { useEffect, useState } from 'react';
import { SlidersHorizontal, Check, ImagePlus, Trash2 } from 'lucide-react';
import { backgrounds, palettes, templates, type Project } from '../domain/model';
import { FontPicker } from './FontPicker';
function ImagePreview({ blob, label }: { blob: Blob | null; label: string }) {
  const [url, setUrl] = useState('');
  useEffect(() => { if (!blob) { setUrl(''); return; } const next = URL.createObjectURL(blob); setUrl(next); return () => URL.revokeObjectURL(next); }, [blob]);
  return url ? <img src={url} alt={label}/> : <span className="monet-empty">无图片</span>;
}
// Presentation controls persist in the project and are shared by both render paths.
export function Inspector({ project: p, change, importFont, installFont, importTemperaImages, removeTemperaImage, coverBlob, monetPortraitBlob, importMonetPortrait, clearMonetPortrait }: { project: Project; change: (patch: Partial<Project>) => void; importFont: () => void; installFont: (blob: Blob, family: string) => Promise<void>; importTemperaImages: () => void; removeTemperaImage: (id: string) => Promise<void>; coverBlob: Blob | null; monetPortraitBlob: Blob | null; importMonetPortrait: () => void; clearMonetPortrait: () => void }) {
  return <aside className="inspector"><div className="panel-title"><h2>画面</h2><SlidersHorizontal size={15}/></div><section className="inspector-section"><div className="section-label">歌词动画 <span>{templates.length} 种</span></div><div className="template-list">{templates.map(t => <button key={t.id} className={`template-option ${p.template === t.id ? 'selected' : ''}`} onClick={() => change({ template: t.id })}><span className={`template-art ${t.id === 'folia-fume' ? 'article' : t.id === 'folia-classic' ? 'flow' : 'tilt'}`} aria-hidden="true">{t.id === 'folia-fume' ? <><i>把日子</i><i>写成诗</i><i>让风读</i></> : t.id === 'folia-classic' ? <><i>风</i><i>与</i><i>诗</i></> : <><i>写成</i><i>一首诗</i></>}</span><span className="template-copy"><strong>{t.name}</strong><small>{t.english}</small></span>{p.template === t.id && <Check size={14}/>}</button>)}</div></section>
    <section className="inspector-section"><div className="section-label">背景画面 <span>独立组合</span></div><div className="background-list">{backgrounds.map(item => <button key={item.id} className={p.background === item.id ? 'selected' : ''} onClick={() => change({ background: item.id })}><span className={`background-chip ${item.id}`}/><span><strong>{item.name}</strong><small>{item.description}</small></span>{p.background === item.id ? <Check size={13}/> : null}</button>)}</div><div className="section-label response-title">音乐响应 <span>预览与导出一致</span></div><div className="segmented response-modes">{([['off','关闭'],['gentle','柔和'],['rhythmic','律动']] as const).map(([value,label]) => <button key={value} className={p.audioReactivity === value ? 'selected' : ''} onClick={() => change({ audioReactivity: value })}>{label}</button>)}</div>{p.audioReactivity !== 'off' ? <label className="range-label">响应强度 <span>{Math.round(p.audioReactivityAmount * 100)}%</span><input aria-label="音乐响应强度" type="range" min="0" max="1" step="0.05" value={p.audioReactivityAmount} onChange={e => change({ audioReactivityAmount: Number(e.target.value) })}/></label> : null}<p className="field-note">低频驱动呼吸与光量，人声和高频只改变少量色彩细节。</p></section>
    {p.template === 'folia-tempera' ? <section className="inspector-section"><div className="section-label">凝彩图片池 <span>{p.temperaLayerImages.length} / 16</span></div><button className="font-upload" disabled={p.temperaLayerImages.length >= 16} onClick={importTemperaImages}><ImagePlus size={13}/>添加立绘、Logo 或纹理</button><div className="tempera-pool">{p.temperaLayerImages.map(image => <div className="tempera-item" key={image.id}><div className="tempera-title"><span title={image.name}>{image.name}</span><button aria-label={`移除 ${image.name}`} onClick={() => void removeTemperaImage(image.id)}><Trash2 size={12}/></button></div><div className="tempera-controls"><label>横向<select aria-label={`${image.name} 横向位置`} value={image.align} onChange={e => change({ temperaLayerImages: p.temperaLayerImages.map(item => item.id === image.id ? { ...item, align: e.target.value as typeof image.align } : item) })}><option value="left">左</option><option value="center">中</option><option value="right">右</option><option value="free">自由</option></select></label><label>纵向<select aria-label={`${image.name} 纵向位置`} value={image.verticalAlign} onChange={e => change({ temperaLayerImages: p.temperaLayerImages.map(item => item.id === image.id ? { ...item, verticalAlign: e.target.value as typeof image.verticalAlign } : item) })}><option value="top">上</option><option value="center">中</option><option value="bottom">下</option><option value="free">自由</option></select></label></div><label className="tempera-range">缩放 <span>{Math.round(image.scale * 100)}%</span><input aria-label={`${image.name} 缩放`} type="range" min="0.1" max="2" step="0.05" value={image.scale} onChange={e => change({ temperaLayerImages: p.temperaLayerImages.map(item => item.id === image.id ? { ...item, scale: Number(e.target.value) } : item) })}/></label><label className="tempera-range">透明度 <span>{Math.round(image.opacity * 100)}%</span><input aria-label={`${image.name} 透明度`} type="range" min="0" max="1" step="0.05" value={image.opacity} onChange={e => change({ temperaLayerImages: p.temperaLayerImages.map(item => item.id === image.id ? { ...item, opacity: Number(e.target.value) } : item) })}/></label></div>)}</div></section> : null}
    {p.template === 'folia-monet' ? <section className="inspector-section monet-panel"><div className="section-label">莫奈人物图 <span>随工程保存</span></div><div className="monet-assets"><button className={p.monetPortraitSource === 'cover' ? 'selected' : ''} disabled={!coverBlob} onClick={() => change({ monetPortraitSource: 'cover' })}><ImagePreview blob={coverBlob} label="音频内嵌封面"/><span><strong>歌曲封面</strong><small>{coverBlob ? '来自音频文件' : '当前音频没有封面'}</small></span>{p.monetPortraitSource === 'cover' && coverBlob ? <Check size={12}/> : null}</button><button className={p.monetPortraitSource === 'custom' ? 'selected' : ''} onClick={importMonetPortrait}><ImagePreview blob={monetPortraitBlob} label="自定义人物图"/><span><strong>自定义图片</strong><small>{p.monetPortraitName || '点击上传图片'}</small></span>{p.monetPortraitSource === 'custom' && monetPortraitBlob ? <Check size={12}/> : null}</button></div><div className="monet-actions"><button onClick={importMonetPortrait}><ImagePlus size={12}/>{monetPortraitBlob ? '更换图片' : '上传图片'}</button><button disabled={!monetPortraitBlob} onClick={clearMonetPortrait}><Trash2 size={12}/>移除</button></div><div className="section-label monet-subtitle">图片形状</div><div className="segmented"><button className={p.monetPortraitStyle === 'square' ? 'selected' : ''} onClick={() => change({ monetPortraitStyle: 'square' })}>方形封面</button><button className={p.monetPortraitStyle === 'rectangular' ? 'selected' : ''} onClick={() => change({ monetPortraitStyle: 'rectangular' })}>竖向人物</button></div><label className="range-label">水平位置 <span>{p.monetPortraitOffsetX > 0 ? '+' : ''}{p.monetPortraitOffsetX}px</span><input aria-label="莫奈图片水平位置" type="range" min="-240" max="240" step="5" value={p.monetPortraitOffsetX} onChange={e => change({ monetPortraitOffsetX: Number(e.target.value) })}/></label><div className="section-label monet-subtitle">音频频谱</div><label className="toggle-label"><span>显示底部频谱</span><input type="checkbox" checked={p.monetAudioVisualization} onChange={e => change({ monetAudioVisualization: e.target.checked })}/></label>{p.monetAudioVisualization ? <div className="segmented response-modes"><button className={p.monetAudioStyle === 'bar' ? 'selected' : ''} onClick={() => change({ monetAudioStyle: 'bar' })}>频谱条</button><button className={p.monetAudioStyle === 'line' ? 'selected' : ''} onClick={() => change({ monetAudioStyle: 'line' })}>曲线</button></div> : null}</section> : null}
    <section className="inspector-section"><div className="section-label">画幅比例</div><div className="segmented">{(['16:9', '9:16', '1:1'] as const).map(r => <button key={r} className={p.ratio === r ? 'selected' : ''} onClick={() => change({ ratio: r })}><span className={`ratio-icon r${r.replace(':', '')}`}/>{r}</button>)}</div></section>
    <section className="inspector-section"><div className="section-label">色彩氛围</div><div className="swatches">{(Object.keys(palettes) as Project['palette'][]).map(key => <button key={key} title={key === 'paper' ? '暖纸' : key === 'midnight' ? '夜幕' : '苔绿'} aria-label={key === 'paper' ? '暖纸配色' : key === 'midnight' ? '夜幕配色' : '苔绿配色'} className={p.palette === key ? 'selected' : ''} style={{ background: palettes[key].bg, color: palettes[key].ink }} onClick={() => change({ palette: key })}><span style={{ background: palettes[key].accent }}/>{p.palette === key && <Check size={13}/>}</button>)}</div></section>
    <section className="inspector-section"><div className="section-label">文字排版</div><FontPicker project={p} change={change} importFont={importFont} installFont={installFont}/><label className="range-label">文字大小 <span>{Math.round(p.fontScale * 100)}%</span><input aria-label="文字大小" type="range" min="0.5" max="1.7" step="0.05" value={p.fontScale} onChange={e => change({ fontScale: Number(e.target.value) })}/></label><label className="range-label">运动幅度 <span>{p.intensity.toFixed(1)}×</span><input aria-label="运动幅度" type="range" min="0.3" max="2" step="0.1" value={p.intensity} onChange={e => change({ intensity: Number(e.target.value) })}/></label></section>
    <section className="inspector-section"><div className="section-label">歌词同步</div><label className="offset-label">整体偏移 <div><input aria-label="歌词整体偏移" type="number" min="-3600" max="3600" step="0.1" value={p.offset} onChange={e => { const value = Number(e.target.value); if (Number.isFinite(value)) change({ offset: Math.min(3600, Math.max(-3600, value)) }); }}/><span>秒</span></div></label><p className="field-note">正值让歌词延后出现。</p><label className="toggle-label"><span>估算逐字显现</span><input type="checkbox" checked={p.estimatedReveal} onChange={e => change({ estimatedReveal: e.target.checked })}/></label><p className="field-note">无逐字时间时，按句长生成视觉节奏。</p></section>
    <div className="inspector-foot"><span className="status-dot"/> Folia 渲染器 · AGPL-3.0</div>
  </aside>;
}
