import { SlidersHorizontal, Check } from 'lucide-react';
import { palettes, templates, type Project } from '../domain/model';
import { FontPicker } from './FontPicker';
// Presentation controls persist in the project and are shared by both render paths.
export function Inspector({ project: p, change, importFont, installFont }: { project: Project; change: (patch: Partial<Project>) => void; importFont: () => void; installFont: (blob: Blob, family: string) => Promise<void> }) {
  return <aside className="inspector"><div className="panel-title"><h2>画面</h2><SlidersHorizontal size={15}/></div><section className="inspector-section"><div className="section-label">歌词动画 <span>{templates.length} 种</span></div><div className="template-list">{templates.map(t => <button key={t.id} className={`template-option ${p.template === t.id ? 'selected' : ''}`} onClick={() => change({ template: t.id })}><span className={`template-art ${t.id === 'folia-fume' ? 'article' : t.id === 'folia-classic' ? 'flow' : 'tilt'}`} aria-hidden="true">{t.id === 'folia-fume' ? <><i>把日子</i><i>写成诗</i><i>让风读</i></> : t.id === 'folia-classic' ? <><i>风</i><i>与</i><i>诗</i></> : <><i>写成</i><i>一首诗</i></>}</span><span className="template-copy"><strong>{t.name}</strong><small>{t.english}</small></span>{p.template === t.id && <Check size={14}/>}</button>)}</div></section>
    <section className="inspector-section"><div className="section-label">画幅比例</div><div className="segmented">{(['16:9', '9:16', '1:1'] as const).map(r => <button key={r} className={p.ratio === r ? 'selected' : ''} onClick={() => change({ ratio: r })}><span className={`ratio-icon r${r.replace(':', '')}`}/>{r}</button>)}</div></section>
    <section className="inspector-section"><div className="section-label">色彩氛围</div><div className="swatches">{(Object.keys(palettes) as Project['palette'][]).map(key => <button key={key} title={key === 'paper' ? '暖纸' : key === 'midnight' ? '夜幕' : '苔绿'} aria-label={key === 'paper' ? '暖纸配色' : key === 'midnight' ? '夜幕配色' : '苔绿配色'} className={p.palette === key ? 'selected' : ''} style={{ background: palettes[key].bg, color: palettes[key].ink }} onClick={() => change({ palette: key })}><span style={{ background: palettes[key].accent }}/>{p.palette === key && <Check size={13}/>}</button>)}</div></section>
    <section className="inspector-section"><div className="section-label">文字排版</div><FontPicker project={p} change={change} importFont={importFont} installFont={installFont}/><label className="range-label">文字大小 <span>{Math.round(p.fontScale * 100)}%</span><input aria-label="文字大小" type="range" min="0.5" max="1.7" step="0.05" value={p.fontScale} onChange={e => change({ fontScale: Number(e.target.value) })}/></label><label className="range-label">运动幅度 <span>{p.intensity.toFixed(1)}×</span><input aria-label="运动幅度" type="range" min="0.3" max="2" step="0.1" value={p.intensity} onChange={e => change({ intensity: Number(e.target.value) })}/></label></section>
    <section className="inspector-section"><div className="section-label">歌词同步</div><label className="offset-label">整体偏移 <div><input aria-label="歌词整体偏移" type="number" min="-3600" max="3600" step="0.1" value={p.offset} onChange={e => { const value = Number(e.target.value); if (Number.isFinite(value)) change({ offset: Math.min(3600, Math.max(-3600, value)) }); }}/><span>秒</span></div></label><p className="field-note">正值让歌词延后出现。</p><label className="toggle-label"><span>估算逐字显现</span><input type="checkbox" checked={p.estimatedReveal} onChange={e => change({ estimatedReveal: e.target.checked })}/></label><p className="field-note">无逐字时间时，按句长生成视觉节奏。</p></section>
    <div className="inspector-foot"><span className="status-dot"/> Folia 渲染器 · AGPL-3.0</div>
  </aside>;
}
