import { useEffect, useState } from 'react';
import { Clipboard, FileUp, Plus, Scissors, Merge, Trash2, Timer, RotateCcw } from 'lucide-react';
import { activeLine, timeLabel, type LyricLine, type Project } from '../domain/model';
import { estimateTiming, parseLyrics } from '../import/lyrics';
import type { PlaybackClock } from '../audio/clock';
import { useTranslation } from 'react-i18next';
// Edits invalidate word timings when their text or interval changes.
export function LyricsPanel({ project, commit, selected, select, clock, paste, importFile, openTimestamp, notify }: { project: Project; commit: (p: Project | ((p: Project) => Project)) => void; selected: string | null; select: (id: string | null) => void; clock: PlaybackClock; paste: () => void; importFile: () => void; openTimestamp: () => void; notify: (s: string) => void }) {
  const { t } = useTranslation();
  const [active, setActive] = useState(-1);
  useEffect(() => { const id = setInterval(() => setActive(activeLine(project.lines, clock.time - project.offset)), 100); return () => clearInterval(id); }, [project.lines, project.offset, clock]);
  const update = (id: string, patch: Partial<LyricLine>) => commit(p => ({ ...p, lines: p.lines.map(l => l.id === id ? { ...l, ...patch, words: [], wordSegments: patch.text !== undefined ? undefined : l.wordSegments, precision: patch.text !== undefined ? l.precision : 'manual' } : l) }));
  const selectedLine = project.lines.find(l => l.id === selected);
  const split = () => {
    if (!selectedLine || Array.from(selectedLine.text).length < 2) return;
    const chars = Array.from(selectedLine.text), half = Math.ceil(chars.length / 2), middle = selectedLine.start !== null && selectedLine.end !== null ? (selectedLine.start + selectedLine.end) / 2 : null;
    const second = { ...selectedLine, id: crypto.randomUUID(), text: chars.slice(half).join(''), start: middle, words: [], wordSegments: undefined };
    commit(p => ({ ...p, lines: p.lines.flatMap(l => l.id === selected ? [{ ...l, text: chars.slice(0, half).join(''), end: middle, words: [], wordSegments: undefined }, second] : [l]) }));
  };
  const merge = () => { const index = project.lines.findIndex(l => l.id === selected); if (index < 0 || index === project.lines.length - 1) return;
    commit(p => ({ ...p, lines: p.lines.flatMap((l, i) => i === index ? [{ ...l, text: `${l.text} ${p.lines[i + 1].text}`, end: p.lines[i + 1].end, words: [], wordSegments: undefined }] : i === index + 1 ? [] : [l]) })); };
  return <div className="lyrics-panel"><div className="panel-title"><h2>{t('lyrics.title')}</h2><span>{t('lyrics.lines',{count:project.lines.length})}</span></div><div className="import-actions" data-tour="lyrics-import"><button onClick={paste}><Clipboard size={14}/>{t('lyrics.paste')}</button><button onClick={importFile}><FileUp size={14}/>{t('lyrics.import')}</button></div>
    <div className="lyrics-meta"><span>{!project.lines.length?t('lyrics.empty'):project.lines.some(l=>l.start===null)?t('lyrics.untimed'):project.lines.some(l=>l.precision==='estimated')?t('lyrics.estimated'):t('lyrics.ready')}</span><button className="clear-lyrics" disabled={!project.lines.length && !project.source} onClick={() => { commit(p => ({ ...p, lines: [], source: '' })); select(null); notify(t('lyrics.cleared')); }}>{t('lyrics.clear')}</button><button className="icon-button" disabled={!project.source} data-tooltip={t('lyrics.restore')} aria-label={t('lyrics.restore')} onClick={() => commit(p => ({ ...p, lines: parseLyrics(p.source, p.duration).lines }))}><RotateCcw size={13}/></button></div>
    {project.lines.some(l => l.start === null) && <button className="estimate-button" onClick={() => { commit(p => ({ ...p, lines: estimateTiming(p.lines, p.duration) })); notify(t('lyrics.estimatedNotice')); }}>{t('lyrics.estimate')}</button>}
    <div className="lyric-list">{project.lines.length ? project.lines.map((l, i) => <div key={l.id} className={`lyric-row ${selected === l.id ? 'selected' : ''} ${active === i ? 'singing' : ''}`} onClick={() => select(l.id)}><div className="lyric-row-meta"><span>{String(i + 1).padStart(2, '0')}</span><button title={t('lyrics.seekLine')} onClick={e => { e.stopPropagation(); select(l.id); if (l.start !== null) clock.seek(l.start + project.offset); }}>{l.start === null ? t('lyrics.pending') : timeLabel(l.start)}</button>{l.words.length > 0 ? <small>{t('lyrics.wordLevel')}</small> : l.precision === 'estimated' ? <small>{t('lyrics.estimatedShort')}</small> : null}</div><textarea aria-label={t('lyrics.lineLabel',{line:i+1})} key={`${l.id}-${l.text}`} defaultValue={l.text} rows={1} onFocus={() => select(l.id)} onBlur={e => { if (e.target.value !== l.text) update(l.id, { text: e.target.value }); }}/></div>) : <p className="empty-note">{t('lyrics.emptyHelp')}</p>}</div>
    <div className="lyric-tools"><button className="icon-button" data-tooltip={t('lyrics.add')} aria-label={t('lyrics.add')} onClick={() => { const id = crypto.randomUUID(); commit(p => ({ ...p, lines: [...p.lines, { id, text: t('lyrics.newLine'), start: null, end: null, precision: 'untimed', words: [] }] })); select(id); }}><Plus size={15}/></button><button className="icon-button" data-tooltip={t('lyrics.split')} aria-label={t('lyrics.split')} disabled={!selectedLine} onClick={split}><Scissors size={15}/></button><button className="icon-button" data-tooltip={t('lyrics.merge')} aria-label={t('lyrics.merge')} disabled={!selectedLine} onClick={merge}><Merge size={15}/></button><button className="icon-button" data-tooltip={t('lyrics.delete')} aria-label={t('lyrics.delete')} disabled={!selectedLine} onClick={() => commit(p => ({ ...p, lines: p.lines.filter(l => l.id !== selected) }))}><Trash2 size={15}/></button><span/><button className="stamp-button" data-tour="timing" disabled={!project.lines.length} onClick={openTimestamp}><Timer size={14}/>{t('lyrics.timing')}</button></div>
  </div>;
}
