import { useEffect, useRef, useState } from 'react';
import { AudioLines, Repeat2, Type, ZoomIn, ZoomOut } from 'lucide-react';
import { timeLabel, type Project } from '../domain/model';
import type { PlaybackClock } from '../audio/clock';
import { useTranslation } from 'react-i18next';
// Timeline pointer geometry maps directly onto the shared media clock.
export function Timeline({ project, peaks, clock, selected, select }: { project: Project; peaks: number[]; clock: PlaybackClock; selected: string | null; select: (id: string) => void }) {
  const { t } = useTranslation(); const playhead = useRef<HTMLDivElement>(null), track = useRef<HTMLDivElement>(null); const [zoom, setZoom] = useState(1), [loop, setLoop] = useState(false);
  useEffect(() => { let id = 0; const update = () => { if (playhead.current) playhead.current.style.left = `${clock.time / project.duration * 100}%`; id = requestAnimationFrame(update); }; update(); return () => cancelAnimationFrame(id); }, [clock, project.duration]);
  useEffect(() => { const l = project.lines.find(l => l.id === selected); clock.loop = loop && l?.start !== null && l?.start !== undefined && l.end !== null ? [Math.max(0, l.start + project.offset), Math.min(project.duration, l.end + project.offset)] : null; }, [loop, selected, project.lines, project.offset, project.duration, clock]);
  return <section className="timeline"><div className="timeline-heading"><span>{t('timeline.title')} <small>{t('timeline.hint')}</small></span><div className="row"><button data-tooltip={t('timeline.loop')} aria-label={t('timeline.loop')} className={loop ? 'active' : ''} onClick={() => setLoop(!loop)}><Repeat2 size={16}/></button><span className="divider"/><button data-tooltip={t('timeline.zoomOut')} aria-label={t('timeline.zoomOut')} onClick={() => setZoom(Math.max(1, zoom - 0.5))}><ZoomOut size={15}/></button><span className="mono tiny">{zoom * 100}%</span><button data-tooltip={t('timeline.zoomIn')} aria-label={t('timeline.zoomIn')} onClick={() => setZoom(Math.min(5, zoom + 0.5))}><ZoomIn size={15}/></button></div></div>
    <div className="timeline-body"><div className="track-labels"><span>{t('timeline.time')}</span><span><AudioLines size={14}/>{t('timeline.audio')}</span><span><Type size={14}/>{t('timeline.lyrics')}</span></div><div className="timeline-scroll"><div className="tracks" style={{ width: `${zoom * 100}%` }} ref={track} onPointerDown={e => { if ((e.target as HTMLElement).closest('button')) return; e.currentTarget.setPointerCapture(e.pointerId); const rect = e.currentTarget.getBoundingClientRect(); clock.seek((e.clientX - rect.left) / rect.width * project.duration); }} onPointerMove={e => { if (!e.currentTarget.hasPointerCapture(e.pointerId)) return; const rect = e.currentTarget.getBoundingClientRect(); clock.seek((e.clientX - rect.left) / rect.width * project.duration); }}>
      <div className="ruler">{Array.from({ length: 11 }, (_, i) => <span key={i} style={{ left: `${i * 10}%` }}>{timeLabel(project.duration * i / 10).slice(0, 5)}</span>)}</div>
      <div className="wave-track"><svg viewBox="0 0 1200 48" preserveAspectRatio="none" aria-label={t('timeline.audio')}>{peaks.map((p, i) => <line key={i} x1={i * 1200 / peaks.length} x2={i * 1200 / peaks.length} y1={24 - p * 21} y2={24 + p * 21} stroke="currentColor" strokeWidth="1.3"/>)}</svg><span>{project.audioName || `${t('editor.demoAudio')}.wav`}</span></div>
      <div className="lyric-track">{project.lines.map(l => l.start === null || l.end === null ? null : <button key={l.id} title={l.text} className={selected === l.id ? 'selected' : ''} style={{ left: `${Math.max(0, l.start + project.offset) / project.duration * 100}%`, width: `${Math.max(0.1, Math.min(project.duration, l.end + project.offset) - Math.max(0, l.start + project.offset)) / project.duration * 100}%` }} onClick={() => { select(l.id); clock.seek(l.start! + project.offset); }}>{l.text}</button>)}</div><div className="playhead" ref={playhead}><span/></div>
    </div></div></div></section>;
}
